Repository softeerbootcamp-3rd/Team4-HansalChai, pull requests merged in 2024-02, with the labels that each got.

#10 Feature/#5 fe setting
  haul-fe/dev-dist/sw.js
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/App.css
  haul-fe/src/App.jsx
  haul-fe/src/assets/fonts/Pretendard-Bold.woff
  haul-fe/src/assets/fonts/Pretendard-ExtraBold.woff
  haul-fe/src/assets/fonts/Pretendard-Medium.woff
  haul-fe/src/assets/fonts/Pretendard-Regular.woff
  haul-fe/src/assets/fonts/Pretendard-SemiBold.woff
  haul-fe/src/assets/fonts/fonts.css
  haul-fe/src/assets/react.svg
  haul-fe/src/components/MobileLayout.jsx
  haul-fe/src/index.css
  haul-fe/src/main.jsx
  haul-fe/src/routes/Router.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/TestView.jsx
Labels: Priority: High, Type : Feature, FE

#14 Feature/#6 common components sean2337
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/App.jsx
  haul-fe/src/assets/svgs/RouteIcon.svg
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/DetailInfo/RouteMap.jsx
  haul-fe/src/components/Flex/Flex.jsx
  haul-fe/src/components/Input/Input.jsx
  haul-fe/src/components/Margin/Margin.jsx
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/components/Typhography/Typhography.jsx
  haul-fe/src/components/UnderBar/UnderBar.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/TestView.jsx
  haul-fe/vite.config.js
Labels: Priority: High, Type : Feature, FE

#15 Feature/#3 initial setting
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/pull_request_template.md
  README.md
  haul-be/.gitignore
  haul-be/build.gradle
  haul-be/gradle/wrapper/gradle-wrapper.jar
  haul-be/gradle/wrapper/gradle-wrapper.properties
  haul-be/gradlew
  haul-be/gradlew.bat
  haul-be/settings.gradle
  haul-be/src/main/java/com/hansalchai/haul/HaulApplication.java
  haul-be/src/main/resources/application.properties
  haul-be/src/test/java/com/hansalchai/haul/HaulApplicationTests.java
Labels: Priority: High, Type : Feature, BE

#16 Feature/#3 direcotry setting
  haul-be/src/main/java/com/hansalchai/haul/car/dummy
  haul-be/src/main/java/com/hansalchai/haul/common/exception/dummy
  haul-be/src/main/java/com/hansalchai/haul/common/handler/dummy
  haul-be/src/main/java/com/hansalchai/haul/common/utils/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/security/dummy
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#21 Feat/#19 configuration
  haul-be/.gitignore
  haul-be/src/main/java/com/hansalchai/haul/common/utils/BaseTime.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/dummy
  haul-be/src/main/resources/application.properties
  haul-be/src/main/resources/logback-spring.xml
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#22 Feature/#6 common components pransinia
  haul-fe/dev-dist/sw.js
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/assets/pngs/porter.png
  haul-fe/src/assets/svgs/SelectedCircle.svg
  haul-fe/src/assets/svgs/SelectedCircle_Selected.svg
  haul-fe/src/assets/svgs/Truck.svg
  haul-fe/src/assets/svgs/Truck_Selected.svg
  haul-fe/src/assets/svgs/home.svg
  haul-fe/src/components/BottomButton.jsx
  haul-fe/src/components/CarInfoBox.jsx
  haul-fe/src/components/Header.jsx
  haul-fe/src/components/NavigationBar.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/TestView.jsx
  haul-fe/vite.config.js
Labels: Priority: High, Status: Available, Type : Feature, FE

#31 hotfix : gradle에서 slf4j 제거
  haul-be/build.gradle
  haul-be/logs/sampleLog.log
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
Labels: Priority: Urgent, Status: In Progress, Type: Bug, BE

#32 Feature/#8 choice transport choice date
  haul-fe/src/ store/reservationStore.jsx
  haul-fe/src/App.jsx
  haul-fe/src/assets/svgs/Transport1.svg
  haul-fe/src/assets/svgs/Transport2.svg
  haul-fe/src/assets/svgs/Transport3.svg
  haul-fe/src/assets/svgs/Transport4.svg
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Login/Login.jsx
Labels: Priority: Medium, Type : Feature, FE

#34 Feature/#9 choice date
  haul-fe/src/App.jsx
  haul-fe/src/components/Typhography/Typhography_Span.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
  haul-fe/src/views/Splash/Splash.jsx
Labels: Priority: Medium, Type : Feature, FE

#35 Feature/#29 more page
  haul-fe/index.html
  haul-fe/src/assets/pngs/card1.png
  haul-fe/src/assets/pngs/card2.png
  haul-fe/src/assets/pngs/card3.png
  haul-fe/src/assets/svgs/SelectedCircle.svg
  haul-fe/src/components/Header/Header.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/data/Contracts.js
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/Check/Check.jsx
  haul-fe/src/views/Contract/Contract.jsx
  haul-fe/src/views/More/More.jsx
  haul-fe/src/views/Terms/Terms.jsx
  haul-fe/src/views/UserInfo/UserInfo.jsx
  haul-fe/src/views/UserPayments/UserPayments.jsx
  haul-fe/src/views/UserPayments/components/Carousel.jsx
Labels: Priority: High, Status: Available, Type : Feature, Type : Refactor, FE

#36 Feature/#10 code refactor
  haul-fe/src/components/CheckMark/CheckMark.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
Labels: Priority: High, Type : Refactor, FE

#37 Feature/#20 고객 회원가입 기능 구현
  haul-be/.gitignore
  haul-be/src/main/java/com/hansalchai/haul/HaulApplication.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/constants/Role.java
  haul-be/src/main/java/com/hansalchai/haul/customer/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/customer/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/driver/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/CustomerSignUpDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/main/java/com/hansalchai/haul/user/repository/UsersRepository.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#41 Feature/#20 로그인 기능 구현
  haul-be/.gitignore
  haul-be/build.gradle
  haul-be/logs/sampleLog.log
  haul-be/src/main/java/com/hansalchai/haul/common/auth/dto/AuthenticatedUser.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/Jwt.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
  haul-be/src/main/java/com/hansalchai/haul/security/dummy
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/UserLoginDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
Labels: Priority: Low, Status: In Progress, Type : Feature, BE

#44 Feature/#42 result page kakao map
  haul-fe/index.html
  haul-fe/src/assets/gifs/Loading_Truck.json
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/DetailInfo/RouteMap.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/Result/Result.jsx
Labels: Priority: High, Type : Feature, FE

#46 fix : 병합 중 누락된 코드 추가
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/UserAuthorizationInterceptor.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/dto/AuthenticatedUser.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/service/AuthService.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
Labels: Priority: Urgent, Status: In Progress, Type: Bug, BE

#48 Feature/#45 request exception handling
  haul-fe/index.html
  haul-fe/src/assets/svgs/미니용달.svg
  haul-fe/src/assets/svgs/비즈니스운송.svg
  haul-fe/src/assets/svgs/용달이사.svg
  haul-fe/src/assets/svgs/일반용달.svg
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/FixedBox/FixedCenterBox.jsx
  haul-fe/src/components/Input/Input.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: Priority: High, Type : Feature, FE

#47 Feature/#29 more page - final
  haul-fe/.gitignore
  haul-fe/index.html
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/assets/pngs/dummy.png
  haul-fe/src/assets/pngs/mighty.png
  haul-fe/src/components/Button/BottomButton.jsx
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/Carousel/Carousel.jsx
  haul-fe/src/components/CheckMark/CheckMark.jsx
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/Flex/Flex.jsx
  haul-fe/src/components/Header/Header.jsx
  haul-fe/src/components/Input/Input.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/Margin/Margin.jsx
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/components/Toast/ToastMaker.jsx
  haul-fe/src/components/Typhography/Typhography.jsx
  haul-fe/src/components/Typhography/Typhography_Span.jsx
  haul-fe/src/components/UnderBar/UnderBar.jsx
  haul-fe/src/data/Contracts.js
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/CheckDetail/components/DriverInfoBox.jsx
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/More/List/More.jsx
  haul-fe/src/views/More/Terms/Contract/Contract.jsx
  haul-fe/src/views/More/Terms/Terms.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/More/UserPayments/UserPayments.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
  haul-fe/src/views/Splash/Splash.jsx
  haul-fe/src/views/UserInfo/UserInfo.jsx
  haul-fe/src/views/UserPayments/UserPayments.jsx
  haul-fe/vite.config.js
Labels: Priority: High, Status: Available, Type: Enhancement, Type : Feature, Type : Refactor, FE

#33 Feature/#18 reservation
  haul-be/.gitignore
  haul-be/build.gradle
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarCategory.java
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarType.java
  haul-be/src/main/java/com/hansalchai/haul/car/dummy
  haul-be/src/main/java/com/hansalchai/haul/car/entity/Car.java
  haul-be/src/main/java/com/hansalchai/haul/car/repository/CarRepository.java
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ApiResponse.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/BaseTime.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CarCategorySelector.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMap.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMapAPI.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/MapUtils.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/QueryDslConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationNumberGenerator.java
  haul-be/src/main/java/com/hansalchai/haul/customer/entity/Customer.java
  haul-be/src/main/java/com/hansalchai/haul/customer/repository/CustomerRepository.java
  haul-be/src/main/java/com/hansalchai/haul/driver/entity/Driver.java
  haul-be/src/main/java/com/hansalchai/haul/driver/repository/DriverRepository.java
  haul-be/src/main/java/com/hansalchai/haul/owner/entity/Owner.java
  haul-be/src/main/java/com/hansalchai/haul/owner/repository/OwnerRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportType.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Cargo.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/CargoOption.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Destination.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Source.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CargoOptionRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CargoRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepositoryImpl.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/DestinationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/SourceRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/TransportRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/dummy
  haul-be/src/main/resources/db/teardown.sql
  haul-be/src/test/java/com/hansalchai/haul/car/CarTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/KaKaoMapTest.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#56 Refactor/#53 client refactor
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/CheckDetail/components/DriverInfoBox.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
Labels: Priority: Medium, Type : Refactor, FE

#58 Feature/#52 refactor - esLint 적용
  haul-fe/.eslintrc.cjs
  haul-fe/.gitignore
  haul-fe/.prettierrc
  haul-fe/src/assets/gifs/LoadingTruck.json
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/Carousel/Carousel.jsx
  haul-fe/src/components/CheckMark/CheckMark.jsx
  haul-fe/src/components/Input/Input.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/components/Typhography/Typhography.jsx
  haul-fe/src/components/Typhography/TyphographySpan.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/More/UserPayments/UserPayments.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
  haul-fe/src/views/Splash/Splash.jsx
Labels: Priority: Low, Status: Available, Type : Refactor, FE

#59 docs : swagger 적용
  haul-be/build.gradle
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
Labels: BE

#55 Test/#20 회원가입 및 로그인 테스트 코드 작성, 리팩토링
  haul-be/src/main/java/com/hansalchai/haul/common/auth/dto/AuthenticatedUser.java
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/CustomerSignUpDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/UserLoginDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
  haul-be/src/test/java/com/hansalchai/haul/user/controller/UsersControllerTest.java
  haul-be/src/test/java/com/hansalchai/haul/user/service/UsersServiceTest.java
Labels: Priority: Low, Status: In Progress, BE

#61 Docs build.gradle의 querydsl 설정 변경
  haul-be/build.gradle
Labels: Priority: High, Status: In Progress, BE

#62 Feature/#54 user reservation detail
  haul-be/src/main/generated/com/hansalchai/haul/car/entity/QCar.java
  haul-be/src/main/generated/com/hansalchai/haul/common/utils/QBaseTime.java
  haul-be/src/main/generated/com/hansalchai/haul/owner/entity/QOwner.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QCargo.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QCargoOption.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QDestination.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QReservation.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QSource.java
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QTransport.java
  haul-be/src/main/generated/com/hansalchai/haul/user/entity/QUsers.java
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarType.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/constants/Role.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMap.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/MapUtils.java
  haul-be/src/main/java/com/hansalchai/haul/customer/entity/Customer.java
  haul-be/src/main/java/com/hansalchai/haul/customer/repository/CustomerRepository.java
  haul-be/src/main/java/com/hansalchai/haul/driver/entity/Driver.java
  haul-be/src/main/java/com/hansalchai/haul/driver/repository/DriverRepository.java
  haul-be/src/main/java/com/hansalchai/haul/owner/entity/Owner.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/CustomerSignUpDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/UserLoginDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/main/resources/db/teardown.sql
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#66 Feature/#65 profile api
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebAuthConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/config/WebConfig.java
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/ProfileDTO.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/ProfileUpdateDTO.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
Labels: Priority: Low, Status: In Progress, Type : Feature, BE

#72 feat : aws s3 세팅 및 이미지 조회 기능 구현
  haul-be/build.gradle
  haul-be/src/main/java/com/hansalchai/haul/common/config/AwsS3Config.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/S3Util.java
Labels: Priority: Low, Status: In Progress, Type : Feature, BE

#75 fix : Location latitude, longitude
  haul-be/src/main/java/com/hansalchai/haul/common/utils/MapUtils.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: Urgent, BE

#77 Feature/#57 member guest login store
  haul-fe/index.html
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/assets/svgs/HomeIcon.svg
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/Header/Header.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/GuestInfo/GuestInfo.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: Priority: High, Type : Feature, FE

#78 Fe dev -> dev
  haul-fe/index.html
  haul-fe/package-lock.json
  haul-fe/package.json
  haul-fe/src/assets/svgs/HomeIcon.svg
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/Header/Header.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/store/reservationStore.jsx
  haul-fe/src/styles/GlobalStyle.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/GuestLogin/GuestLogin.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/GuestInfo/GuestInfo.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: Priority: Medium, Type : Feature, FE

#82 Hotfix/#81 preflight request의 CORS 에러 해결
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/dto/AuthenticatedUser.java
Labels: Priority: Urgent, Type: Bug, BE

#84 Hotfix/reservation request dto
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
Labels: Priority: Urgent, BE

#88 resevationid null error
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
Labels: Priority: Urgent, Type: Bug, BE

#92 Feat/#80 client api connect
  haul-fe/src/components/Input/Input.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/GuestInfo/GuestInfo.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Result/Result.jsx
Labels: Priority: High, Type : Feature, FE

#94 Feat/#90 car enhancement
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarType.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepositoryImpl.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#97 Feature/#90-car-enhancement
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepositoryImpl.java
  haul-be/src/main/resources/db/teardown.sql
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
Labels: Priority: Medium, BE

#98 Feat/#95 code modification document
  haul-fe/src/components/Button/readme.md
  haul-fe/src/components/CarInfoBox/readme.md
  haul-fe/src/components/CheckMark/readme.md
  haul-fe/src/components/DetailInfo/readme.md
  haul-fe/src/components/FixedBox/readme.md
  haul-fe/src/components/Flex/readme.md
  haul-fe/src/components/Header/readme.md
  haul-fe/src/components/Input/readme.md
  haul-fe/src/components/Map/RouteMap/readme.md
  haul-fe/src/components/Map/SearchMap/readme.md
  haul-fe/src/components/Map/readme.md
  haul-fe/src/components/Margin/readme.md
  haul-fe/src/components/MobileLayout/readme.md
  haul-fe/src/components/NavigationBar/readme.md
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/components/Toast/readme.md
  haul-fe/src/components/Typhography/readme.md
  haul-fe/src/components/UnderBar/readme.md
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/data/readme.md
  haul-fe/src/repository/readme.md
  haul-fe/src/routes/readme.md
  haul-fe/src/store/readme.md
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
Labels: Priority: High, Type : Feature, FE

#103 Feature/#52 refactor - 수정
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/GuestCheck/GuestCheck.jsx
  haul-fe/src/views/Check/List/components/Skeleton.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Result/Result.jsx
Labels: Priority: High, Type: Bug, FE

#93 Feat/#51 [기사] 오더 승인 api 구현
  haul-be/build.gradle
  haul-be/src/main/java/com/hansalchai/haul/common/config/SmsUtil.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/ApproveRequestDto.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/owner/repository/OwnerRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#111 Refactor/#110 map refactor
  haul-fe/index.html
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/repository/checkRepository.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/GuestCheck/GuestCheck.jsx
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
  haul-fe/src/views/More/List/More.jsx
  haul-fe/src/views/More/Terms/Contract/Contract.jsx
  haul-fe/src/views/More/Terms/Terms.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/More/UserPayments/UserPayments.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/Result/Result.jsx
Labels: Priority: Medium, Type: Enhancement, FE

#112 Docs/#100 readme
  haul-fe/src/components/Carousel/readme.md
  haul-fe/src/components/NavigationBar/readme.md
  haul-fe/src/styles/readme.md
  haul-fe/src/styles/theme/readme.md
  haul-fe/src/utils/readme.md
  haul-fe/src/views/Check/CheckDetail/readme.md
  haul-fe/src/views/Check/GuestCheck/readme.md
  haul-fe/src/views/Check/List/readme.md
  haul-fe/src/views/Check/readme.md
  haul-fe/src/views/Login/readme.md
  haul-fe/src/views/More/List/readme.md
  haul-fe/src/views/More/Terms/Contract/readme.md
  haul-fe/src/views/More/Terms/readme.md
  haul-fe/src/views/More/UserInfo/readme.md
  haul-fe/src/views/More/UserPayments/readme.md
  haul-fe/src/views/More/readme.md
  haul-fe/src/views/Request/ChoiceDate/readme.md
  haul-fe/src/views/Request/ChoiceDst/readme.md
  haul-fe/src/views/Request/ChoiceLoadInfo/readme.md
  haul-fe/src/views/Request/ChoiceSrc/readme.md
  haul-fe/src/views/Request/ChoiceTime/readme.md
  haul-fe/src/views/Request/ChoiceTransport/readme.md
  haul-fe/src/views/Request/Complete/readme.md
  haul-fe/src/views/Request/GuestInfo/readme.md
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Purchase/readme.md
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/Request/Result/readme.md
  haul-fe/src/views/Request/readme.md
  haul-fe/src/views/SignUp/readme.md
  haul-fe/src/views/Splash/readme.md
Labels: Priority: High, Type : Docs, FE

#114 fix: 지도 출력되지 않는 버그 수정
  haul-fe/index.html
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#115 feat: 기사 버전 프로젝트 세팅
  haul-driver-fe/.gitignore
  haul-driver-fe/package-lock.json
  haul-driver-fe/src/App.css
  haul-driver-fe/src/App.jsx
  haul-driver-fe/src/assets/fonts/Pretendard-Bold.woff
  haul-driver-fe/src/assets/fonts/Pretendard-ExtraBold.woff
  haul-driver-fe/src/assets/fonts/Pretendard-Medium.woff
  haul-driver-fe/src/assets/fonts/Pretendard-Regular.woff
  haul-driver-fe/src/assets/fonts/Pretendard-SemiBold.woff
  haul-driver-fe/src/assets/fonts/fonts.css
  haul-driver-fe/src/assets/react.svg
  haul-driver-fe/src/components/Button/BottomButton.jsx
  haul-driver-fe/src/components/Carousel/Carousel.jsx
  haul-driver-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-driver-fe/src/components/FixedBox/FixedCenterBox.jsx
  haul-driver-fe/src/components/Flex/Flex.jsx
  haul-driver-fe/src/components/Header/Header.jsx
  haul-driver-fe/src/components/Input/Input.jsx
  haul-driver-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-driver-fe/src/components/Margin/Margin.jsx
  haul-driver-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-driver-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-driver-fe/src/components/Toast/Toast.jsx
  haul-driver-fe/src/components/Toast/ToastMaker.jsx
  haul-driver-fe/src/components/Toast/ToastRoot.jsx
  haul-driver-fe/src/components/Typhography/Typhography.jsx
  haul-driver-fe/src/components/Typhography/TyphographySpan.jsx
  haul-driver-fe/src/data/Contracts.js
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/index.css
  haul-driver-fe/src/main.jsx
  haul-driver-fe/src/routes/Router.jsx
  haul-driver-fe/src/styles/GlobalStyle.jsx
  haul-driver-fe/src/styles/theme/Theme.jsx
  haul-driver-fe/src/utils/helper.js
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/Login/Login.jsx
Labels: Priority: High, Type : Feature, FE

#117 Feature/#52 refactor - 탭바 추가
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/TabBar.jsx
  haul-fe/src/views/More/List/More.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
Labels: Priority: Medium, Type : Feature, FE

#120 Config/#119 테스트 환경 설정
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
  haul-be/src/main/resources/db/teardown.sql
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: Medium, Status: In Progress, BE

#121 Feat/#118 driver page publishing
  haul-driver-fe/src/assets/gifs/Loading.gif
  haul-driver-fe/src/assets/gifs/LoadingTruck.json
  haul-driver-fe/src/assets/svgs/HaulCar.svg
  haul-driver-fe/src/assets/svgs/HaulIcon.svg
  haul-driver-fe/src/assets/svgs/HomeIcon.svg
  haul-driver-fe/src/assets/svgs/RouteIcon.svg
  haul-driver-fe/src/assets/svgs/UserCheck.svg
  haul-driver-fe/src/components/Carousel/Carousel.jsx
  haul-driver-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-driver-fe/src/components/DriveTimeBox/DriveTimeBox.jsx
  haul-driver-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-driver-fe/src/components/UnderBar/UnderBar.jsx
  haul-driver-fe/src/components/UserInfoBox/UserInfoBox.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/routes/Router.jsx
  haul-driver-fe/src/utils/helper.js
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/ScheduleCheckDetail.jsx
  haul-driver-fe/src/views/ScheduleCreate/Complete/Complete.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/ScheduleCreateDetail.jsx
  haul-driver-fe/src/views/Splash/Splash.jsx
Labels: Priority: Medium, Type : Feature, FE

#124 Feature/#110 기사 페이지 퍼블리싱
  haul-driver-fe/index.html
  haul-driver-fe/src/assets/svgs/MoveIcon.svg
  haul-driver-fe/src/assets/svgs/SelectedCircle.svg
  haul-driver-fe/src/assets/svgs/SelectedCircle_Selected.svg
  haul-driver-fe/src/assets/svgs/Truck.svg
  haul-driver-fe/src/assets/svgs/Truck_Selected.svg
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/InfiniteList/components/Skeleton.jsx
  haul-driver-fe/src/components/InfiniteList/components/SummaryItemBox.jsx
  haul-driver-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-driver-fe/src/components/TabBar/TabBar.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/routes/Router.jsx
  haul-driver-fe/src/views/More/List/More.jsx
  haul-driver-fe/src/views/More/Terms/Contract/Contract.jsx
  haul-driver-fe/src/views/More/Terms/Terms.jsx
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/Complete/Complete.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
  haul-driver-fe/vite.config.js
Labels: Priority: Medium, Status: Available, Type : Feature, FE

#123 Feat/#96 기사 오더 탐색 리스트 조회 api 구현
  haul-be/src/main/java/com/hansalchai/haul/common/utils/AddressUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationUtil.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderFilter.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderSearchResponse.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/AddressUtilTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/ReservationUtilTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#122 Feat/#107 driver self order
  haul-be/src/main/java/com/hansalchai/haul/guest/constants/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/controller/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/dto/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/entity/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/repository/dummy
  haul-be/src/main/java/com/hansalchai/haul/guest/service/dummy
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderStatusCategory.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/test/java/com/hansalchai/haul/order/OrderTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#127 Feat/#125 page publishing test
  haul-driver-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-driver-fe/src/components/DriveTimeBox/DriveTimeBox.jsx
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/InfiniteList/components/SummaryItemBox.jsx
  haul-driver-fe/src/components/TabBar/TabBar.jsx
  haul-driver-fe/src/components/UserInfoBox/UserInfoBox.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/routes/Router.jsx
  haul-driver-fe/src/styles/GlobalStyle.jsx
  haul-driver-fe/src/styles/theme/Theme.jsx
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/ScheduleCheckDetail.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/ScheduleCreateDetail.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: Medium, Type : Feature, FE

#129 Feat/#126 오더 운송 상태 변경 api 구현
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/ApproveRequestDto.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderSearchResponse.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/TransportStatusChange.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/test/java/com/hansalchai/haul/order/dto/TransportStatusChangeTest.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#130 Feat/#128 change publishing update
  haul-driver-fe/src/assets/svgs/GPSIcon.svg
  haul-driver-fe/src/assets/svgs/HaulRouteIcon.svg
  haul-driver-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-driver-fe/src/components/DriveTimeBox/DriveTimeBox.jsx
  haul-driver-fe/src/components/FixedBox/FixedCenterBox.jsx
  haul-driver-fe/src/components/HaulInfoBox/HaulInfoBox.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/routes/Router.jsx
  haul-driver-fe/src/styles/theme/Theme.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/ScheduleCheckDetail.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/components/DriverStatusButton.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/ScheduleCreateDetail.jsx
Labels: Priority: Medium, Type : Feature, FE

#132 Feature/#110 publish dispatch
  haul-driver-fe/src/components/Carousel/Carousel.jsx
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/UserInfoBox/UserInfoBox.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/styles/theme/Theme.jsx
  haul-driver-fe/src/utils/helper.js
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: Medium, Status: Available, Type : Feature, Type : Refactor, FE

#134 Fix 로그인 responseDto 수정
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/UserLogin.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/UserLoginDto.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
  haul-be/src/test/java/com/hansalchai/haul/user/controller/UsersControllerTest.java
  haul-be/src/test/java/com/hansalchai/haul/user/service/UsersServiceTest.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#136 Feat/#131 driver api connect
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/Loading/Loading.jsx
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/ScheduleCheckDetail.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/components/DriverStatusButton.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/ScheduleCreateDetail.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: Medium, Type : Feature, FE

#139 Feat/#137 code refactor sean2337
  haul-driver-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/Login/index.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/ScheduleCheckDetail.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/components/DriverStatusButton.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCreate/Complete/Complete.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/ScheduleCreateDetail.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/index.jsx
Labels: Priority: Medium, Type : Refactor, FE

#140 Feature/#135 profile dev
  haul-driver-fe/src/assets/svgs/EmptyIcon.svg
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/InfiniteList/components/SummaryItemBox.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/styles/theme/Theme.jsx
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/EmptyListHolder.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/Complete/Complete.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/EmptyListHolder.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: High, Type: Bug, Type: Enhancement, Type : Feature, Type : Refactor, FE

#143 Fix/minor bug fix
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationRestController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, BE

#145 feat : transactional on service
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
Labels: Priority: Urgent, Status: In Progress, Type : Feature, BE

#138 Feat/#86 인증, 인가 예외처리 기능 구현
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/UserAuthorizationInterceptor.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/constants/JwtExceptionType.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/handler/FilterExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
  haul-be/src/main/java/com/hansalchai/haul/common/exceptions/ConflictException.java
  haul-be/src/main/java/com/hansalchai/haul/common/exceptions/NotFoundException.java
  haul-be/src/main/java/com/hansalchai/haul/common/exceptions/UnauthorizedException.java
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ApiResponse.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
Labels: Priority: Medium, Status: In Progress, Type: Enhancement, BE

#148 Feat/#85 오더 관련 예외처리
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderFilter.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
Labels: Priority: Medium, Status: In Progress, Type : Feature, BE

#153 Hotfix/#144 fix list
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: Urgent, Type : Feature, FE, Type: Hotfix

#147 Feature/#135 profile
  haul-fe/src/assets/svgs/EmptyIcon.svg
  haul-fe/src/repository/userRepository.js
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/EmptyListHolder.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Check/List/components/TabBar.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/More/UserPayments/UserPayments.jsx
Labels: Priority: Low, Type : Feature, FE

#152 Feat/#146 reservation exception
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarType.java
  haul-be/src/main/java/com/hansalchai/haul/common/exceptions/ForbiddenException.java
  haul-be/src/main/java/com/hansalchai/haul/common/exceptions/InternalServerError.java
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMapAPI.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationNumberGenerator.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationUtil.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderStatusCategory.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportType.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/CargoOption.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Destination.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Source.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: High, Status: In Progress, Type : Feature, Type : Refactor, BE

#159 feat : api code -> int
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ApiResponse.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
Labels: Priority: Urgent

#161 Hotfix/#158 tabbar
  haul-fe/src/repository/checkRepository.js
  haul-fe/src/utils/helper.js
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/EmptyListHolder.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
Labels: Priority: Urgent, Status: Available, FE, Type: Hotfix

#162 fix/#160 토큰 관련 에러 코드 수정
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
Labels: Priority: High, Type : Feature, BE

#165 fix : 토큰 예외처리 방식 수정
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
Labels: Priority: High, BE, Type: Hotfix

#168 Feat/#155 error handling sean2337
  haul-fe/index.html
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/components/Map/RouteMap/RouteMap.jsx
  haul-fe/src/components/Map/SearchMap/SearchMap.jsx
  haul-fe/src/components/MobileLayout/MobileLayout.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/routes/Router.jsx
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
  haul-fe/src/views/Loading/Loading.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/More/List/More.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/Request/ChoiceDate/ChoiceDate.jsx
  haul-fe/src/views/Request/ChoiceDst/ChoiceDst.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/ChoiceSrc/ChoiceSrc.jsx
  haul-fe/src/views/Request/ChoiceTime/ChoiceTime.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Request/GuestInfo/GuestInfo.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
  haul-fe/src/views/Request/Result/Result.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: Priority: High, Type : Feature, FE

#166 fix : 버그 수정
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
Labels: Priority: Low, BE

#176 fix : 토큰 유효성 검증 실패 시, 500 Internal Server Error가 발생하는 오류 해결
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/handler/FilterExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
Labels: Priority: Urgent, BE, Type: Hotfix

#175 Feat/#170 driver error handling
  haul-driver-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-driver-fe/src/components/Toast/ToastRoot.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/Login/index.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/index.jsx
Labels: Priority: High, Type : Feature, FE

#178 Hotfix 토큰 유효성 검증 실패 시, 에러코드 전송에 NPE 에러 해결
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
Labels: Priority: Urgent, Type: Bug, BE

#180 Hotfix/#179 reservation list error handling
  haul-fe/src/main.jsx
  haul-fe/src/views/Check/List/Check.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#183 Feature/#154 error handling - 기사 앱
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/TabBar/TabBar.jsx
  haul-driver-fe/src/components/UserInfoBox/UserInfoBox.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/main.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/components/DriverStatusButton.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
Labels: Priority: High, Status: Available, Type : Feature, Type : Refactor, FE

#184 Feature/#153 error handling - 고객 핫픽스
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#186 delete: useNavigate().navigate()제거
  haul-fe/src/repository/userRepository.js
Labels: Priority: Urgent, FE

#187 FE_dev -> dev
  haul-fe/src/main.jsx
  haul-fe/src/repository/userRepository.js
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/Request/ChoiceLoadInfo/ChoiceLoadInfo.jsx
  haul-fe/src/views/Request/Purchase/Purchase.jsx
Labels: Priority: High, FE

#188 Feature/#154 error handling - 기사 앱 무한 스크롤 수정
  haul-driver-fe/package.json
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/InfiniteList/components/SummaryItemBox.jsx
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckList/ScheduleCheckList.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
  haul-fe/src/repository/reservationRepository.js
Labels: Priority: Urgent, FE, Type: Hotfix

#189 Feature/#153 error handling - 고객 앱 무한 스크롤 수정
  haul-fe/index.html
  haul-fe/package.json
  haul-fe/src/repository/checkRepository.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#191 Revert "Feature/#153 error handling - 고객 앱 무한 스크롤 수정"
  haul-fe/index.html
  haul-fe/package.json
  haul-fe/src/repository/checkRepository.js
  haul-fe/src/repository/reservationRepository.js
  haul-fe/src/repository/userRepository.js
  haul-fe/src/views/Check/List/Check.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
Labels: FE

#202 Refactor/#169 improving performance
  haul-fe/src/assets/fonts/fonts.css
  haul-fe/src/assets/fonts/subset-Pretendard-Bold.woff2
  haul-fe/src/assets/fonts/subset-Pretendard-ExtraBold.woff2
  haul-fe/src/assets/fonts/subset-Pretendard-Medium.woff2
  haul-fe/src/assets/fonts/subset-Pretendard-Regular.woff2
  haul-fe/src/assets/fonts/subset-Pretendard-SemiBold.woff2
  haul-fe/src/assets/gifs/Haul_Complete_Loading.gif
  haul-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-fe/src/routes/Router.jsx
  haul-fe/src/styles/theme/Theme.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Request/Complete/Complete.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
  haul-fe/src/views/TestView.jsx
Labels: Priority: Medium, Type: Enhancement, FE

#167 Feat/#149 오더 승인 기능 보완 - 중첩 스케줄 방지
  haul-be/build.gradle
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
Labels: Priority: High, Status: In Progress, Type: Enhancement, BE

#203 오더 운송상태 변경 기능 보완
  haul-be/src/main/java/com/hansalchai/haul/common/utils/OrderUtil.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/TransportStatusChange.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/OrderUtilTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/dto/TransportStatusChangeTest.java
Labels: Priority: Medium, Status: In Progress, Type: Enhancement, BE

#206 Feat/#171 오더 승인 api의 동시성 처리
  haul-be/src/main/java/com/hansalchai/haul/order/dto/ApproveRequestDto.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/owner/entity/Owner.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Reservation.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceIntegrationTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceUnitTest.java
Labels: Priority: High, Status: In Progress, Type: Enhancement, BE

#204 enhance/#163 reservation seperate
  haul-be/src/main/generated/com/hansalchai/haul/reservation/entity/QSource.java
  haul-be/src/main/java/com/hansalchai/haul/common/config/WebConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/AddressUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMap.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMapAPI.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/SidoGraph.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderFilterV2.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/DriverPositionDto.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Cargo.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Source.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomReservationRepositoryImpl.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/KaKaoMapTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/SidoGraphTest.java
Labels: Priority: Medium, Status: In Progress, Type: Enhancement, BE

#212 Refactor/#210 separate
  haul-fe/src/components/Button/BottomButton.jsx
  haul-fe/src/components/CarInfoBox/CarInfoBox.jsx
  haul-fe/src/components/Carousel/Carousel.jsx
  haul-fe/src/components/Carousel/Components/Item.jsx
  haul-fe/src/components/Carousel/Components/Radio.jsx
  haul-fe/src/components/Header/Header.jsx
  haul-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-fe/src/components/Toast/Toast.jsx
  haul-fe/src/data/Contracts.js
  haul-fe/src/repository/checkRepository.js
  haul-fe/src/utils/helper.js
  haul-fe/src/views/Check/CheckDetail/CheckDetail.jsx
  haul-fe/src/views/Check/GuestCheck/GuestCheck.jsx
  haul-fe/src/views/Check/GuestCheck/components/AdvisorFrame.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Check/List/components/Skeleton.jsx
  haul-fe/src/views/Check/List/components/SummaryItemBox.jsx
  haul-fe/src/views/Check/List/components/TabBar.jsx
  haul-fe/src/views/More/List/More.jsx
  haul-fe/src/views/More/Terms/Terms.jsx
  haul-fe/src/views/More/UserInfo/UserInfo.jsx
  haul-fe/src/views/More/UserInfo/components/EditForm.jsx
  haul-fe/src/views/More/UserInfo/components/ViewForm.jsx
  haul-fe/src/views/More/UserInfo/index.jsx
  haul-fe/src/views/More/UserPayments/UserPayments.jsx
Labels: Priority: Medium, Type : Refactor, FE

#221 [hotfix] get요청 바디제거
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/DriverPositionDto.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
Labels: Priority: Urgent, Status: In Progress, Type: Bug, BE

#220 Feat/#215 verson2 driver api
  haul-driver-fe/src/repository/checkRepository.jsx
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/repository/userRepository.jsx
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/ScheduleCheck/ScheduleCheckDetail/index.jsx
  haul-driver-fe/src/views/Splash/Splash.jsx
Labels: Priority: High, Type : Feature, FE

#218 Test/#208 오더 관련 테스트 코드 작성
  haul-be/src/main/java/com/hansalchai/haul/car/entity/Car.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/TransportStatusChange.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceIntegrationTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceUnitTest.java
Labels: Priority: Medium, Status: In Progress, BE

#224 Refactor#222 client refactor
  haul-fe/src/assets/gifs/LoadingTruck.json
  haul-fe/src/assets/svgs/CardPreset.svg
  haul-fe/src/components/MotionWrapper/MotionWrapper.jsx
  haul-fe/src/data/GlobalVariable.js
  haul-fe/src/views/More/UserPayments/components/CardSvg.jsx
  haul-fe/src/views/Request/ChoiceTransport/ChoiceTransport.jsx
  haul-fe/src/views/Splash/Splash.jsx
Labels: Priority: Medium, Type : Refactor, FE

#225 Hotfix/order controller
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMapAPI.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationUtil.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/KaKaoMapTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/ReservationUtilTest.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationTest.java
Labels: Priority: High, Status: In Progress, BE

#228 Feature/#216 clientv2
  haul-fe/index.html
  haul-fe/public/apple-touch-icon.png
  haul-fe/src/App.jsx
  haul-fe/src/components/AppInstallPrompt/AppInstallPrompt.jsx
  haul-fe/src/components/Carousel/Carousel.jsx
  haul-fe/src/components/Carousel/Components/Radio.jsx
  haul-fe/src/utils/helper.js
  haul-fe/src/utils/localStorage.js
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/Request/ChoiceDate/components/Calendar.jsx
Labels: Priority: High, Type : Feature, FE

#231 Feature/#216 driverv2
  haul-driver-fe/index.html
  haul-driver-fe/src/assets/svgs/Truck.svg
  haul-driver-fe/src/assets/svgs/Truck_Selected.svg
  haul-driver-fe/src/components/AppInstallPrompt/AppInstallPrompt.jsx
  haul-driver-fe/src/components/Button/BottomButton.jsx
  haul-driver-fe/src/components/InfiniteList/InfiniteList.jsx
  haul-driver-fe/src/components/NavigationBar/NavigationBar.jsx
  haul-driver-fe/src/data/GlobalVariable.js
  haul-driver-fe/src/repository/createRepository.jsx
  haul-driver-fe/src/utils/helper.js
  haul-driver-fe/src/utils/localStorage.js
  haul-driver-fe/src/views/Login/Login.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateDetail/index.jsx
  haul-driver-fe/src/views/ScheduleCreate/ScheduleCreateList/ScheduleCreateList.jsx
  haul-driver-fe/vite.config.js
Labels: Priority: High, Type: Enhancement, Type : Feature, FE

#235 Feature/#216 clientv2 - 문제 수정
  haul-fe/src/components/AppInstallPrompt/AppInstallPrompt.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: Priority: Urgent, Type : Feature, Type : Refactor, FE, Type: Hotfix

#233 Refactor/#230 인증/인가 기능 리팩토링
  haul-be/src/main/java/com/hansalchai/haul/common/auth/anotation/LoggedInUser.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/LoggedInUserArgumentResolver.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebAuthConfig.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationController.java
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
Labels: Priority: Medium, Type : Refactor, BE

#238 Feature/#216 driverv2 캐로셀 수리
  haul-driver-fe/src/components/Carousel/Carousel.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#240 [refactor] lint 및 안쓰는 함수 삭제
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarCategory.java
  haul-be/src/main/java/com/hansalchai/haul/car/constants/CarType.java
  haul-be/src/main/java/com/hansalchai/haul/car/entity/Car.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/LoggedInUserArgumentResolver.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/handler/FilterExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/jwt/JwtProvider.java
  haul-be/src/main/java/com/hansalchai/haul/common/config/SmsUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/config/WebConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/handler/GlobalExceptionHandler.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/AddressUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ApiResponse.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/BaseTime.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CarCategorySelector.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/CargoFeeTable.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ErrorCode.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMap.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/KaKaoMap/KakaoMapAPI.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/MapUtils.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationNumberGenerator.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/ReservationUtil.java
  haul-be/src/main/java/com/hansalchai/haul/common/utils/SidoGraph.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderFilter.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderFilterV2.java
  haul-be/src/main/java/com/hansalchai/haul/order/constants/OrderStatusCategory.java
  haul-be/src/main/java/com/hansalchai/haul/order/controller/OrderController.java
  haul-be/src/main/java/com/hansalchai/haul/order/dto/OrderResponse.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportStatus.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/constants/TransportType.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/controller/ReservationController.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationRequest.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/dto/ReservationResponse.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Cargo.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/entity/Transport.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomCarRepositoryImpl.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/CustomReservationRepositoryImpl.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/repository/ReservationRepository.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
  haul-be/src/main/java/com/hansalchai/haul/user/controller/UsersController.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/ProfileDTO.java
  haul-be/src/main/java/com/hansalchai/haul/user/dto/ProfileUpdateDTO.java
  haul-be/src/main/java/com/hansalchai/haul/user/entity/Users.java
  haul-be/src/main/java/com/hansalchai/haul/user/service/UsersService.java
  haul-be/src/test/java/com/hansalchai/haul/car/CarTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/CargoFeeTableTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/KaKaoMapTest.java
  haul-be/src/test/java/com/hansalchai/haul/common/utils/SidoGraphTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceIntegrationTest.java
  haul-be/src/test/java/com/hansalchai/haul/order/service/OrderServiceUnitTest.java
  haul-be/src/test/java/com/hansalchai/haul/reservation/ReservationIntegrationTest.java
  haul-be/src/test/java/com/hansalchai/haul/user/controller/UsersControllerTest.java
  haul-be/src/test/java/com/hansalchai/haul/user/service/UsersServiceTest.java
Labels: Priority: Low, Status: In Progress, Type: Enhancement, BE

#241 Fe dev -> dev
  haul-fe/src/components/AppInstallPrompt/AppInstallPrompt.jsx
  haul-fe/src/views/Check/List/components/InfiniteList.jsx
  haul-fe/src/views/Login/Login.jsx
  haul-fe/src/views/SignUp/SignUp.jsx
Labels: FE

#245 리스트 핫픽스
  haul-driver-fe/src/repository/createRepository.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#246 Fe driver -> dev 핫픽스
  haul-driver-fe/src/repository/createRepository.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#247 fix: API 변경 적용
  haul-driver-fe/src/repository/createRepository.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#248 Fe driver dev
  haul-driver-fe/src/repository/createRepository.jsx
Labels: Priority: Urgent, FE, Type: Hotfix

#251 Hotfix 인터셉터 수정
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/UserAuthorizationInterceptor.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebAuthConfig.java
Labels: Priority: Medium, BE, Type: Hotfix

#253 [fix] 기사 앱 발견한 오류 수정
  haul-driver-fe/src/components/DetailInfo/DetailInfo.jsx
  haul-driver-fe/src/components/HaulInfoBox/HaulInfoBox.jsx
Labels: Priority: Urgent, Status: Available, FE, Type: Hotfix

#255 Hotfix 필터, 인터셉터를 통과하지 않는 url 리스트 수정
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/JwtValidationFilter.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebAuthConfig.java
  haul-be/src/main/java/com/hansalchai/haul/common/config/WebConfig.java
Labels: Priority: Urgent, Type: Hotfix

#256 Add/#244 비회원 예약 확정 메시지 전송 기능 추가 및 기사 배정 알림 메시지의 주석 해제
  haul-be/src/main/java/com/hansalchai/haul/common/config/SmsUtil.java
  haul-be/src/main/java/com/hansalchai/haul/order/service/OrderService.java
  haul-be/src/main/java/com/hansalchai/haul/reservation/service/ReservationService.java
Labels: Priority: Medium, Type : Feature, BE

#257 Hotfix 인터셉터의 preflight, swagger 문제 해결
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/UserAuthorizationInterceptor.java
  haul-be/src/main/java/com/hansalchai/haul/common/auth/config/WebAuthConfig.java
Labels: Priority: High, BE
